# Generated by Django 4.2.15 on 2024-09-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0003_alter_restaurant_options_alter_table_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('tables', models.ManyToManyField(related_name='bookings', to='restaurants.table')),
            ],
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('booking_date', 'start_time', 'end_time'), name='unique_booking_time'),
        ),
    ]
