# Generated by Django 4.2.15 on 2024-10-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
